# Generated by Django 5.0.3 on 2024-03-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
