# Generated by Django 5.0.3 on 2024-03-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_name_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.IntegerField()),
                ('quote_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
