# Generated by Django 5.0.3 on 2024-03-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='api.user'),
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='movies', to='api.user'),
        ),
    ]
