# Generated by Django 5.0.3 on 2024-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_exercise_user_remove_movie_user_exercise_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='exercise',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.exercise'),
        ),
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.movie'),
        ),
    ]
