# Generated by Django 5.0.3 on 2024-03-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_exercise_user_remove_movie_user_user_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
